/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppTopBar: typeof import('./src/components/AppTopBar.vue')['default']
    AuthForm: typeof import('./src/components/AuthForm.vue')['default']
    BrandLogo: typeof import('./src/components/images/BrandLogo.vue')['default']
    BrandLogoAnimation: typeof import('./src/components/BrandLogoAnimation.vue')['default']
    BreadCrumb: typeof import('./src/components/BreadCrumb.vue')['default']
    HeroSection: typeof import('./src/components/HeroSection.vue')['default']
    ICarbonLogout: typeof import('~icons/carbon/logout')['default']
    IMdiEyeOffOutline: typeof import('~icons/mdi/eye-off-outline')['default']
    IMdiEyeOutline: typeof import('~icons/mdi/eye-outline')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    LoadingIcon: typeof import('./src/components/LoadingIcon.vue')['default']
    LoadingScreen: typeof import('./src/components/LoadingScreen.vue')['default']
    NavDrawer: typeof import('./src/components/NavDrawer.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    Quickviews: typeof import('./src/components/Quickviews.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerErrorAlert: typeof import('./src/components/ServerErrorAlert.vue')['default']
    StandardCard: typeof import('./src/components/StandardCard.vue')['default']
    TagLink: typeof import('./src/components/TagLink.vue')['default']
    VButton: typeof import('./src/components/VButton.vue')['default']
    VIconButton: typeof import('./src/components/VIconButton.vue')['default']
    VInput: typeof import('./src/components/VInput.vue')['default']
    VLabel: typeof import('./src/components/VLabel.vue')['default']
    VPasswordInput: typeof import('./src/components/VPasswordInput.vue')['default']
  }
}
